platform :ios, '8.0'

target 'SnapExam' do
    use_frameworks!
    
    pod 'SwiftyJSON', '~> 3.0.0’
    
    pod 'ObjectMapper', '~> 2.0.0'

end

target 'SnapExamTests' do

end

target 'SnapExamUITests' do
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
